services:
  backend:
    build:
      context: ./simplipy-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build:
      context: ./simplipy-frontend
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

